name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Static Analysis
        run: |
          # Run pyflakes to check for simple errors and style issues
          pyflakes .

          # Run mypy for static type checking
          mypy .

      - name: Build and Deploy
        run: python app/main.py  